"""
Feedback Loop Pipeline: Multi-state RL architecture for LLM-driven market agent optimization.

RL framing:
  State  s  = MarketConfig (market parameters: timesteps, q_max, shade_range, …)
  Action a  = strategy code (Python function generated by the LLM)
  Reward R  = surplus earned by strategy a in the diagnostic run for state s
  Policy π  = LLM: given (s, diagnostic_json, value_table) → propose new strategy
  Value  V  = ValueTable: V(s) ≈ max_{a seen} R(s, a)

Outer Loop: Episodes (k = 1, 2, …, K)
  - Pick next state s_k from the config rotation
  - Generate N candidate strategies (policy inference)
  - Run one diagnostic sim per candidate at the fixed seed for s_k
  - Select winner = highest surplus
  - Update V(s_k) with winner surplus
  - Store diagnostic JSON in buffer for next episode's context

Inner Loop: Code refinement (per candidate, up to M attempts)
  - Verify strategy passes unit tests
  - On failure, show error and retry
"""

import json
import inspect
import re
from typing import Callable, Dict, List, Any, Optional, Tuple
from pathlib import Path
from openai import OpenAI

from marketsim.LLM.code_storage import CodeStorage
from marketsim.LLM.code_generation_pipeline import CodeGenerationPipeline
from marketsim.LLM.episode_runner import run_episode
from marketsim.LLM.memory_buffer import RollingMemoryBuffer, generate_meta_learning_prompt, ScoredPopulation, FamilyBandit
from marketsim.LLM.market_config import MarketConfig, ValueTable
from marketsim.LLM.strategy_test_runner import run_tests_for_function
from marketsim.LLM.utils import existing_path, load_json_if_exists
from marketsim.fourheap.constants import BUY, SELL

DEFAULT_MARKET_DESCRIPTION = (
    "A continuous double auction market where buyers and sellers submit limit orders. "
    "Agents have private valuations and try to maximize their surplus."
)

# Default multi-state config list — covers small, medium, and fast markets
DEFAULT_MARKET_CONFIGS = [
    MarketConfig(num_zi_buy=5,  num_zi_sell=5,  timesteps=1000, q_max=10, pv_var=1e5,
                 shade_range=[0, 500], label="baseline"),
    MarketConfig(num_zi_buy=10, num_zi_sell=10, timesteps=1000, q_max=10, pv_var=1e5,
                 shade_range=[0, 500], label="large"),
    MarketConfig(num_zi_buy=5,  num_zi_sell=5,  timesteps=500,  q_max=10, pv_var=1e5,
                 shade_range=[0, 500], label="short"),
    MarketConfig(num_zi_buy=5,  num_zi_sell=5,  timesteps=1000, q_max=10, pv_var=1e5,
                 shade_range=[0, 250], label="tight_shade"),
]


class FeedbackLoopPipeline:
    """
    Multi-state RL feedback loop for continuous strategy improvement.

    Outer Loop: Cycle through market configs (states), run diagnostic sims, update V(s).
    Inner Loop: Generate and verify candidate strategy code (actions).
    """

    def __init__(
        self,
        llm_order_type: int = BUY,
        llm_private_values: Optional[List[float]] = None,  # deprecated, ignored
        market_configs: Optional[List[MarketConfig]] = None,
        # Legacy single-config params — used only if market_configs is None
        num_zi_opponents: int = 5,
        timesteps_per_episode: int = 1000,
        q_max: int = 10,
        pv_var: float = 1e5,
        # RL / pipeline params
        num_candidates: int = 3,
        buffer_size: int = 5,
        max_inner_iterations: int = 3,
        num_eval_seeds: int = 50,
        storage_dir: str = "llm_calls",
        offline_data_path: Optional[str] = None,
        reward_alpha: float = 1.0,   # weight for CS-efficiency bonus (R/CS)
        reward_beta: float = 2.0,    # weight for super-CS bonus (R > CS)
        reward_gamma: float = 0.05,  # exec-rate nudge weight (fraction of CS per unit deviation)
    ):
        """
        Args:
            llm_order_type:    BUY or SELL
            market_configs:    List of MarketConfig objects defining the state space.
                               Cycled through round-robin across episodes.
                               If None, a single config is built from the legacy params.
            num_zi_opponents:  (Legacy) ZI agents per side when market_configs is None.
            timesteps_per_episode: (Legacy) timesteps when market_configs is None.
            q_max:             Max units per agent.
            pv_var:            Private value variance.
            num_candidates:    Candidate strategies per episode (N in paper).
            buffer_size:       Rolling buffer size.
            max_inner_iterations: Max refinement attempts per candidate (M).
            num_eval_seeds:    Number of seeds to evaluate each candidate over (default 50).
            storage_dir:       Directory for generated code logs.
            offline_data_path: Path to offline ZI trajectory JSON (used in episode 0).
        """
        self.llm_order_type = llm_order_type
        self.q_max = q_max
        self.pv_var = pv_var
        self.num_candidates = num_candidates
        self.max_inner_iterations = max_inner_iterations
        self.num_eval_seeds = num_eval_seeds
        self.storage_dir = storage_dir
        self.reward_alpha = reward_alpha
        self.reward_beta = reward_beta
        self.reward_gamma = reward_gamma

        # Build state space
        if market_configs is not None:
            self.market_configs: List[MarketConfig] = market_configs
        else:
            # Legacy single-config mode
            self.market_configs = [MarketConfig(
                num_zi_buy=num_zi_opponents,
                num_zi_sell=num_zi_opponents,
                timesteps=timesteps_per_episode,
                q_max=q_max,
                pv_var=pv_var,
                shade_range=[0, 500],
                label="default",
            )]

        # RL value function: V(s) = best surplus seen in state s
        self.value_table = ValueTable()

        # Rolling buffer: keeps last `buffer_size` diagnostic JSONs for context
        self.buffer = RollingMemoryBuffer(buffer_size=buffer_size)
        self.code_storage = CodeStorage(storage_dir)

        # Per-config scored population: top-10 programs per market config (FunSearch island)
        # Keys are config_hash strings.
        self._populations: Dict[str, ScoredPopulation] = {}

        # UCB1 bandit over exploration families — shared across configs
        # Initialised lazily after _exploration_families() is available.
        self._family_bandit: Optional[FamilyBandit] = None
        self._dynamic_families: Optional[List[str]] = None

        # OPRO-style surplus history: all (episode, surplus) pairs ever seen, ascending order
        self._surplus_history: List[Tuple[int, float]] = []

        # Per-episode winner tracking (for refine prompt)
        self.last_winner_reasoning: Optional[str] = None
        self.last_winner_code: Optional[str] = None
        self.last_winner_family: Optional[str] = None  # family tag of last winner
        # Last diagnostic JSON result (raw dict) for the most recent episode
        self.last_diagnostic_json: Optional[Dict] = None

        # Load offline trajectory data (used in episode 0 context)
        offline_path = existing_path(offline_data_path)
        self.offline_data = load_json_if_exists(offline_path)

        self.code_gen = CodeGenerationPipeline(
            market_description=DEFAULT_MARKET_DESCRIPTION,
            data_path=str(offline_path) if offline_path is not None else None,
            storage_dir=storage_dir,
        )

        self._family_library_dir = Path(storage_dir) / "family_libraries"
        self._family_library_dir.mkdir(parents=True, exist_ok=True)

        # Episode tracking
        self.episode_count = 0
        self.episode_results: List[Dict[str, Any]] = []
    
    # ------------------------------------------------------------------ #
    #  Context builders — raw JSON, no natural language formatting         #
    # ------------------------------------------------------------------ #

    def _strip_lob_depth(self, events: list) -> list:
        """Remove bids_relative/asks_relative depth arrays from each event — keep only best_bid/ask."""
        stripped = []
        for e in events:
            ev = dict(e)
            if "lob" in ev:
                lob = dict(ev["lob"])
                lob.pop("bids_relative", None)
                lob.pop("asks_relative", None)
                ev["lob"] = lob
            stripped.append(ev)
        return stripped

    def _offline_data_json(self, max_events: int = 15) -> str:
        """
        Return the offline trajectory data as a compact JSON string.

        Handles the current unified schema (events-based, all prices relative)
        as well as the legacy format (absolute prices, transactions key).
        At most max_events records are included — all agent-involved events are
        always kept; background events are sub-sampled to fit the budget.
        """
        if not self.offline_data:
            return json.dumps({"note": "no offline data available"})

        data = dict(self.offline_data)

        # ── Convert legacy absolute-price format if needed ──────────────
        if "participant_private_values" in data and "agent_type" not in data:
            pv_info = data.pop("participant_private_values", {})
            data["agent_type"] = pv_info.get("agent_type", "buyer")
            import statistics
            all_prices = [t["price"] for t in data.get("transactions", []) if "price" in t]
            fundamental_est = statistics.median(all_prices) if all_prices else 100_000.0
            data["agent_total_surplus"] = None
            data["agent_transactions"] = sum(
                1 for t in data.get("transactions", []) if t.get("agent_transacted") or t.get("involved")
            )
            txns = data.pop("transactions", [])
            new_events = []
            for t in txns:
                lob = t.get("lob", {})
                bids_rel = [round(p - fundamental_est, 2) for p in lob.get("bids", [])][:4]
                asks_rel = [round(p - fundamental_est, 2) for p in lob.get("asks", [])][:4]
                new_events.append({
                    "time": t.get("time"),
                    "event_type": "trade",
                    "agent_transacted": bool(t.get("involved", False)),
                    "agent_bid": bool(t.get("involved", False)),
                    "trade_price_relative": round(t["price"] - fundamental_est, 4),
                    "lob": {"best_bid_relative": None, "best_ask_relative": None,
                            "bids_relative": bids_rel, "asks_relative": asks_rel},
                })
            data["events"] = new_events

        # ── Strip opponent internals; agent's own private values are kept ──
        # agent_private_values_relative is intentionally NOT stripped — the LLM
        # needs to see its own valuation schedule to write good strategies.
        for key in ("avg_zi_same_surplus", "market_config",
                    "pv_var", "shade_range", "num_zi_buy", "num_zi_sell", "note",
                    "transactions", "private_values_relative"):
            data.pop(key, None)

        # ── Trim events: always keep agent trades; subsample the rest ──
        events = data.get("events", [])
        agent_trade_events  = [e for e in events if e.get("agent_transacted")]
        agent_order_events  = [e for e in events if e.get("agent_bid") and not e.get("agent_transacted")]
        background_events   = [e for e in events if not e.get("agent_bid") and not e.get("agent_transacted")]
        remaining = max(0, max_events - len(agent_trade_events))
        order_budget      = remaining // 2
        background_budget = remaining - order_budget
        if len(agent_order_events) > order_budget:
            step = len(agent_order_events) / order_budget if order_budget > 0 else 1
            agent_order_events = [agent_order_events[int(i * step)] for i in range(order_budget)]
        if len(background_events) > background_budget:
            step = len(background_events) / background_budget if background_budget > 0 else 1
            background_events = [background_events[int(i * step)] for i in range(background_budget)]
        data["events"] = sorted(
            agent_trade_events + agent_order_events + background_events,
            key=lambda e: e["time"]
        )
        return json.dumps(data, separators=(",", ":"))

    def _diagnostic_json_str(self, diagnostic: Dict, max_events: int = 15) -> str:
        """
        Serialise a diagnostic run result dict (from run_episode with capture_detail=True)
        to a compact JSON string for the LLM prompt.

        Strips any fields the LLM should not see (opponent distributions, private
        values, market internals).  Sub-samples background events to max_events total
        while keeping all agent-involved events.
        """
        payload = dict(diagnostic.get("diagnostic_json", diagnostic))
        # Strip opponent internals; agent_private_values_relative is intentionally kept.
        for key in ("avg_zi_same_surplus", "market_config",
                "pv_var", "shade_range", "num_zi_buy", "num_zi_sell", "note",
                "transactions", "private_values_relative", "inference_summary"):
            payload.pop(key, None)

        # Trim events: always keep agent trades; subsample the rest
        events = payload.get("events", [])
        agent_trade_events  = [e for e in events if e.get("agent_transacted")]
        agent_order_events  = [e for e in events if e.get("agent_bid") and not e.get("agent_transacted")]
        background_events   = [e for e in events if not e.get("agent_bid") and not e.get("agent_transacted")]
        remaining = max(0, max_events - len(agent_trade_events))
        order_budget      = remaining // 2
        background_budget = remaining - order_budget
        if len(agent_order_events) > order_budget:
            step = len(agent_order_events) / order_budget if order_budget > 0 else 1
            agent_order_events = [agent_order_events[int(i * step)] for i in range(order_budget)]
        if len(background_events) > background_budget:
            step = len(background_events) / background_budget if background_budget > 0 else 1
            background_events = [background_events[int(i * step)] for i in range(background_budget)]
        payload["events"] = sorted(
            agent_trade_events + agent_order_events + background_events,
            key=lambda e: e["time"]
        )
        return json.dumps(payload, separators=(",", ":"))

    def _value_table_json(self) -> str:
        """Serialise the current value table to JSON for the LLM."""
        return self.value_table.to_json(max_history=3)

    def _shaped_reward(
        self,
        raw_surplus: float,
        consumer_surplus: Optional[float],
        exec_ratio: float = 1.0,
        neutral_exec_ratio: float = 1.0,
    ) -> float:
        """
        Reshape raw surplus to incentivise closing the gap to consumer surplus,
        reward super-CS performance, and apply a small additive exec-rate nudge.

        R_shaped = base  +  gamma * CS * (exec_ratio - neutral_exec_ratio)

        where:
          base      = R  +  alpha*(R/CS)  +  beta*max(0,(R-CS)/CS)
          nudge     = gamma * CS * (exec_ratio - neutral_exec_ratio)

        The nudge is additive and capped in magnitude at gamma*CS, so it can
        break ties between strategies with similar surplus, but cannot override
        a meaningful surplus difference.  Surplus always dominates.

        neutral_exec_ratio = avg fraction of units with pv > 0 across seeds.
          exec == neutral  → nudge = 0   (no adjustment)
          exec >  neutral  → nudge > 0   (small bonus for executing more)
          exec <  neutral  → nudge < 0   (small penalty for under-executing)

        gamma=0.05 means the max possible nudge is ±5% of CS (~±57 for CS=1140),
        which is small enough that a $50 surplus lead always wins regardless of
        exec rate, but large enough to resolve ties in favour of higher execution.

        When CS is unknown (None or zero), falls back to raw_surplus.
        """
        if not consumer_surplus or consumer_surplus <= 0:
            return raw_surplus

        efficiency = raw_surplus / consumer_surplus
        super_cs   = max(0.0, (raw_surplus - consumer_surplus) / consumer_surplus)
        base = raw_surplus + self.reward_alpha * raw_surplus * efficiency + self.reward_beta * raw_surplus * super_cs

        neutral = max(neutral_exec_ratio, 1e-6)
        nudge = self.reward_gamma * consumer_surplus * (exec_ratio - neutral)

        return base + nudge

    def _get_population(self, config: MarketConfig) -> ScoredPopulation:
        """Return (or lazily create) the ScoredPopulation for a config."""
        key = config.config_hash()
        if key not in self._populations:
            self._populations[key] = ScoredPopulation(max_size=10)
        return self._populations[key]

    def _get_bandit(self, config: Optional[MarketConfig] = None) -> FamilyBandit:
        """Return (or lazily create) the UCB bandit over exploration families."""
        if config is None:
            config = self.market_configs[0]
        families = self._exploration_families(config)
        if self._family_bandit is None:
            self._family_bandit = FamilyBandit(families)
        return self._family_bandit

    def _default_exploration_families(self) -> List[str]:
        return [
            "Optimal fixed shade (ZI baseline): choose one constant shade that maximises expected average surplus for this state. Return (shade, 1).",
            "Bounded random ZI shading range: pick lower/upper shade levels [lo, hi] and draw a uniform shade each decision. Tune [lo, hi] to maximise average surplus. Return (shade, 1).",
            "Private-value-tiered ZI range: use only private_values to split units into high/medium/low value tiers and assign each tier a simple fixed shade (or tight range). Keep logic simple and ZI-like. Return (shade, 1).",
        ]

    @staticmethod
    def _extract_json_object(text: str) -> Optional[Dict[str, Any]]:
        """Extract and parse first JSON object from LLM response text."""
        text = text.strip()
        fenced = re.findall(r"```json\s*(.*?)\s*```", text, flags=re.DOTALL | re.IGNORECASE)
        candidates = [fenced[0]] if fenced else [text]
        for candidate in candidates:
            try:
                return json.loads(candidate)
            except Exception:
                pass
            m = re.search(r"\{.*\}", candidate, flags=re.DOTALL)
            if m:
                try:
                    return json.loads(m.group(0))
                except Exception:
                    pass
        return None

    def _sanitize_family_descriptions(self, raw: List[str]) -> List[str]:
        """Keep only safe, runtime-valid family descriptions; append return contract."""
        cleaned: List[str] = []
        seen = set()
        banned_tokens = [
            "events", "bids_relative", "asks_relative", "lob", "inference_summary",
        ]
        numeric_bound_pattern = re.compile(r"\[[ \t]*\d+(?:\.\d+)?[ \t]*,[ \t]*\d+(?:\.\d+)?[ \t]*\]|<=\s*\d+(?:\.\d+)?|>=\s*\d+(?:\.\d+)?")

        for item in raw:
            if not isinstance(item, str):
                continue
            s = " ".join(item.strip().split())
            if len(s) < 24:
                continue
            lowered = s.lower()
            if any(tok in lowered for tok in banned_tokens):
                continue
            if numeric_bound_pattern.search(s):
                s = numeric_bound_pattern.sub("adaptive range", s)
                s = " ".join(s.split())
            if "return (shade, 1)" not in lowered:
                s = f"{s.rstrip('.')} Return (shade, 1)."
            if s not in seen:
                seen.add(s)
                cleaned.append(s)

        return cleaned

    def _bootstrap_families_from_data(self, config: MarketConfig) -> List[str]:
        """
        Ask the LLM once to propose exploration-family descriptions from offline data.
        Falls back to defaults on any failure.
        """
        offline_json = self._offline_data_json(max_events=20)
        config_json = json.dumps(config.to_dict(), separators=(",", ":"))

        prompt = "\n".join([
            "You are designing exploration strategy families for a ZI-style bidder.",
            "Create 4 to 6 family descriptions using ONLY information observable in real runtime inputs:",
            "private_values, market_history{timestep,total_trades,market_trades}, market_state{max_bid,best_bid,best_ask,units_available,q_max,fundamental_estimate}.",
            "Do NOT reference any offline-only fields (events, LOB depth arrays, opponent internals, shade_range, or hidden simulator settings).",
            "Do NOT include hardcoded numeric shade bounds in the family text.",
            "Each family should be one short sentence and must end with 'Return (shade, 1).',",
            "",
            "Output STRICT JSON only in this schema:",
            "{\"families\":[{\"name\":\"...\",\"description\":\"...\"}]}",
            "",
            "Market config JSON:",
            config_json,
            "",
            "Offline baseline JSON:",
            offline_json,
        ])

        max_prompt_chars = getattr(self.code_gen.generator, "MAX_PROMPT_CHARS", 16000)
        if len(prompt) > max_prompt_chars:
            head = prompt[:7000]
            tail = prompt[-8500:]
            prompt = (
                f"{head}\n\n"
                "[...prompt truncated for context window safety...]\n\n"
                f"{tail}"
            )

        try:
            response = None
            last_error: Optional[Exception] = None
            content = ""
            base_urls = getattr(self.code_gen.generator, "_base_url_candidates", None)
            if not base_urls:
                base_urls = [getattr(self.code_gen.generator, "base_url", None)]
            base_urls = [u for u in base_urls if u]

            for _attempt in range(2):
                for candidate_url in base_urls:
                    try:
                        self.code_gen.generator.client = OpenAI(
                            base_url=candidate_url,
                            api_key=self.code_gen.generator.api_key,
                        )
                        response = self.code_gen.generator.client.chat.completions.create(
                            model=self.code_gen.generator.model_name,
                            messages=[
                                {"role": "system", "content": "You are a strict JSON generator."},
                                {"role": "user", "content": prompt},
                            ],
                            temperature=0.2,
                            max_tokens=900,
                        )
                        self.code_gen.generator.base_url = candidate_url
                        break
                    except Exception as inner_error:
                        last_error = inner_error
                        continue
                if response is not None:
                    break

            if response is None and last_error is not None:
                raise last_error

            content = response.choices[0].message.content or ""
            parsed = self._extract_json_object(content) or {}
            entries = parsed.get("families", []) if isinstance(parsed, dict) else []
            raw_desc: List[str] = []
            for e in entries:
                if not isinstance(e, dict):
                    continue
                name = str(e.get("name") or "").strip()
                desc = str(e.get("description") or "").strip()
                is_placeholder = (not desc) or (desc.lower() in {"return (shade, 1).", "return(shade,1)."})
                if is_placeholder and name:
                    pretty_name = re.sub(r"(?<!^)(?=[A-Z])", " ", name).strip().lower()
                    desc = (
                        f"{name}: use {pretty_name} signals available at runtime to choose an adaptive "
                        "but simple ZI-style shade. Return (shade, 1)."
                    )
                raw_desc.append(desc or name)
            families = self._sanitize_family_descriptions(raw_desc)
            if len(families) < 3:
                debug_path = self._family_library_dir / "last_bootstrap_raw.txt"
                debug_info_path = self._family_library_dir / "last_bootstrap_debug.json"
                with open(debug_path, "w") as f:
                    f.write(content)
                with open(debug_info_path, "w") as f:
                    json.dump(
                        {
                            "entries_count": len(entries),
                            "raw_desc_count": len(raw_desc),
                            "sanitized_count": len(families),
                            "raw_desc": raw_desc,
                        },
                        f,
                        indent=2,
                    )
                if len(families) == 0:
                    raise ValueError("insufficient valid families from bootstrap")
                for fallback in self._default_exploration_families():
                    if fallback not in families:
                        families.append(fallback)
                    if len(families) >= 3:
                        break

            lib_path = self._family_library_dir / f"families_{config.config_hash()}.json"
            with open(lib_path, "w") as f:
                json.dump(
                    {
                        "config": config.to_dict(),
                        "num_families": len(families),
                        "families": families,
                    },
                    f,
                    indent=2,
                )
            print(f"[Family Bootstrap] Loaded {len(families)} LLM-generated families from offline data.")
            return families
        except Exception as e:
            print(f"[Family Bootstrap] Falling back to default families ({e}).")
            return self._default_exploration_families()

    def _opro_trajectory_str(self) -> str:
        """
        OPRO-style: full surplus history sorted ascending (worst → best).
        The LLM sees the trend and treats the last entry as the target to beat.
        """
        if not self._surplus_history:
            return "(no history yet)"
        rows = sorted(self._surplus_history, key=lambda x: x[1])  # ascending
        lines = [f"  ep={ep:3d}  surplus=${s:.0f}" for ep, s in rows]
        return "\n".join(lines)

    def _population_context_str(self, config: MarketConfig, k: int = 3) -> str:
        """
        Build a compact text block showing the top-k diverse programs from
        the scored population for this config, for recombination prompts.
        """
        pop = self._get_population(config)
        entries = pop.diverse_sample(k)
        if not entries:
            return "(no population entries yet)"
        blocks = []
        for i, e in enumerate(entries, 1):
            blocks.append(
                f"### Population program {i}  "
                f"(surplus=${e.avg_surplus:.0f}, family='{e.family_tag}', ep={e.episode})\n"
                f"```python\n{e.code.strip()}\n```"
            )
        return "\n\n".join(blocks)

    def _build_base_context(self, config: MarketConfig) -> str:
        """
        Build the context block shown to all candidate prompts.

        Episode 0: offline trajectory JSON + current market config.
        Episode >0: diagnostic JSON from last episode + value table JSON +
                    OPRO surplus trajectory + current config.
        All context is raw JSON — no natural language reformatting.
        """
        config_json = json.dumps(config.to_dict(), separators=(",", ":"))

        if self.episode_count == 0:
            offline_json = self._offline_data_json()
            return "\n".join([
                "## Market Config",
                config_json,
                "",
                "## Offline ZI Baseline (learn price ranges and typical surplus from this)",
                "lob keys appear only here — NOT at runtime. Runtime keys: best_bid,best_ask,max_bid,units_available,q_max",
                offline_json,
            ])

        # Episode > 0: show last diagnostic result + value table + OPRO history
        diag_str = (
            self._diagnostic_json_str(self.last_diagnostic_json)
            if self.last_diagnostic_json else "{}"
        )
        vt_str = self._value_table_json()
        opro_str = self._opro_trajectory_str()

        parts = [
            "## Market Config",
            config_json,
            "",
            "## Surplus History (worst→best; beat the last entry)",
            opro_str,
        ]
        parts += [
            "",
            "## Last Winning Strategy Trajectory",
            "agent_transacted=true: agent traded. Runtime keys: best_bid,best_ask,max_bid,units_available,q_max",
            diag_str,
            "",
            "## Best Surplus Per Config",
            vt_str,
        ]
        return "\n".join(parts)

    def generate_strategy_code(
        self,
        iteration: int = 0,
        error_feedback: Optional[str] = None,
        previous_attempt: Optional[str] = None,
        config: Optional[MarketConfig] = None,
    ) -> str:
        """
        Fallback single-candidate strategy generation (used when num_candidates==1).
        Main multi-candidate generation is in generate_candidate_strategies().
        """
        if config is None:
            config = self.market_configs[self.episode_count % len(self.market_configs)]
        base_ctx = self._build_base_context(config)
        constraint = self._side_constraint()

        if error_feedback:
            prompt = "\n".join([
                "The following agent_strategy function failed verification:",
                f"Error: {error_feedback}",
                "Rewrite it so it passes.",
                f"  - {constraint}",
                "  - Return a non-negative shade float — the simulator applies it directly as bid = pv - shade.",
                "  - Always guard best_bid/best_ask for None before comparing.",
            ])
        else:
            family = self._exploration_families(config)[0]
            prompt = "\n".join([
                base_ctx,
                "",
                self._strategy_example(),
                "",
                "## Your task: design a bidding strategy",
                f"Implement this approach: {family}",
                "",
                "## Constraints",
                f"  - {constraint}",
                "  - Return a non-negative shade float — the simulator applies it directly (bid = pv - shade).",
                "  - Always guard best_bid/best_ask for None before using them.",
                "",
                "Respond with exactly ONE ```python``` block.",
                "The function signature MUST be: def agent_strategy(private_values, market_history, market_state)",
                "Include a 1-2 sentence docstring.",
            ])

        return self._generate_with_llm(prompt, iteration=iteration + 1,
                                        previous_attempt=previous_attempt)

    def _generate_with_llm(
        self,
        prompt: str,
        iteration: int = 1,
        error_feedback: Optional[str] = None,
        previous_attempt: Optional[str] = None,
    ) -> str:
        """
        Call the LLM with a compact prompt. Returns extracted Python code.
        Falls back to a fixed-shade strategy if the LLM fails.
        """
        full_prompt = prompt
        if previous_attempt:
            full_prompt += f"\n\nPrevious attempt:\n{previous_attempt}"
        if error_feedback:
            full_prompt += f"\n\nError from previous attempt:\n{error_feedback}"
        full_prompt += (
            "\n\nRespond with ONLY a Python code block. "
            "At the top of the function, include a docstring of 2-3 sentences explaining: "
            "(1) what each key term/variable in your strategy means, and "
            "(2) why you believe this approach will earn more surplus. "
            "Then implement the strategy. "
            "The function MUST always return (shade, 1) where shade >= 0 — never return None. "
            "Always check best_bid/best_ask for None before comparing. "
            "Only import from: math, numpy, random, statistics — NO other imports (no sklearn, scipy, pandas, etc.)."
        )

        try:
            code, success, error = self.code_gen.generator.generate_and_validate(
                full_prompt, max_retries=1
            )
            if code:
                # Extract and print the docstring reasoning separately
                reasoning = self._extract_reasoning(code)
                print(f"[LLM] Generated code ({len(code)} chars)")
                if reasoning:
                    print(f"[LLM] Reasoning: {reasoning}")
                return code
            print(f"Warning: LLM returned empty code ({error}), using fallback")
        except Exception as e:
            print(f"Warning: LLM generation failed ({e}), using fallback strategy")
        
        # Fallback: simple fixed-shade strategy that always works
        fallback_code = '''
def agent_strategy(private_values, market_history, market_state):
    """Fallback: fixed shade of 100. Simulator bids pv - 100."""
    return (100, 1)
'''
        return fallback_code

    @staticmethod
    def _extract_reasoning(code: str) -> Optional[str]:
        """
        Extract the docstring from the agent_strategy function as the reasoning.
        Returns a single-line summary (newlines collapsed to spaces).
        """
        import ast
        try:
            tree = ast.parse(code)
            for node in ast.walk(tree):
                if isinstance(node, ast.FunctionDef) and node.name == "agent_strategy":
                    if (node.body and isinstance(node.body[0], ast.Expr)
                            and isinstance(node.body[0].value, ast.Constant)
                            and isinstance(node.body[0].value.value, str)):
                        raw = node.body[0].value.value.strip()
                        # Collapse to a single line for clean terminal output
                        return " ".join(raw.split())
        except Exception:
            pass
        return None
    
    def verify_strategy(
        self,
        strategy_code: str,
        iteration: int = 0,
    ) -> Tuple[bool, Optional[str]]:
        """
        Verify strategy passes unit tests (verification oracle V).
        
        Uses the original test_runner to check against test suite if available,
        otherwise runs basic sanity checks:
        - Code parses and executes
        - Returns valid (price, quantity) tuple or None
        - Buyer doesn't bid above valuation
        - Seller doesn't ask below cost
        - Handles empty market gracefully
        
        Args:
            strategy_code: Python code to verify
            iteration: Iteration number for logging
        
        Returns:
            (passes: bool, error_trace: str or None)
        """
        
        # Block any non-stdlib / non-whitelisted imports
        _allowed_imports = {"math", "numpy", "np", "random", "statistics", "collections", "itertools", "functools"}
        import ast as _ast
        try:
            _tree = _ast.parse(strategy_code)
            for _node in _ast.walk(_tree):
                if isinstance(_node, (_ast.Import, _ast.ImportFrom)):
                    for _alias in getattr(_node, 'names', []):
                        _mod = _alias.name.split('.')[0]
                        if _mod not in _allowed_imports:
                            return False, f"Disallowed import: {_mod} (only math/numpy/random/statistics allowed)"
                    if isinstance(_node, _ast.ImportFrom) and _node.module:
                        _mod = _node.module.split('.')[0]
                        if _mod not in _allowed_imports:
                            return False, f"Disallowed import: {_node.module} (only math/numpy/random/statistics allowed)"
        except SyntaxError:
            pass  # will be caught below

        # Try to parse and compile
        try:
            exec(compile(strategy_code, '<generated>', 'exec'))
        except SyntaxError as e:
            error = f"Syntax error: {e}"
            return False, error
        except ModuleNotFoundError as e:
            return False, f"Disallowed import: {e}"
        
        # Extract function — provide common imports so generated code using np/math works
        try:
            import numpy as _np
            import math as _math
            namespace = {"np": _np, "numpy": _np, "math": _math}
            exec(strategy_code, namespace)
            strategy_func = namespace.get('agent_strategy')
            if not strategy_func:
                return False, "No 'agent_strategy' function defined"
        except (Exception, ModuleNotFoundError) as e:
            return False, f"Execution error: {e}"
        
        # Test with sample inputs - all values on RELATIVE scale (~0, range -500..500)
        test_cases = [
            {
                "name": "Empty market",
                "private_values": [200.0, 150.0, 100.0, 50.0, 0.0],
                "market_history": {"timestep": 0, "market_trades": [], "total_trades": 0},
                "market_state": {
                    "best_bid": None, "best_ask": None,
                    "units_available": 5, "q_max": 10,
                    "fundamental_estimate": 0.0,
                    "max_bid": 200.0, "min_ask": 200.0,
                    "inference": {
                        "ask_n_obs": 0, "ask_mean": None, "ask_std": None, "ask_min": None, "ask_max": None,
                        "ask_p10": None, "ask_p25": None, "ask_p50": None, "ask_p75": None, "ask_p90": None, "ask_trend": None,
                        "bid_n_obs": 0, "bid_mean": None, "bid_std": None, "bid_min": None, "bid_max": None,
                        "bid_p10": None, "bid_p25": None, "bid_p50": None, "bid_p75": None, "bid_p90": None, "bid_trend": None,
                        "trade_n_obs": 0, "trade_mean": None, "trade_std": None, "trade_min": None, "trade_max": None,
                        "trade_p10": None, "trade_p25": None, "trade_p50": None, "trade_p75": None, "trade_p90": None, "trade_trend": None,
                        "spread_mean": None,
                    },
                },
                "max_rational_bid": 200.0,
            },
            {
                "name": "Normal market",
                "private_values": [200.0, 150.0, 100.0, 50.0, 0.0],
                "market_history": {
                    "timestep": 300,
                    "market_trades": [{"time": 10, "price": -50.0}, {"time": 20, "price": -30.0},
                                      {"time": 30, "price": -10.0}],
                    "total_trades": 10,
                },
                "market_state": {
                    "best_bid": -100.0, "best_ask": 50.0,
                    "units_available": 4, "q_max": 10,
                    "fundamental_estimate": 5.0,
                    "max_bid": 150.0, "min_ask": 150.0,
                    "inference": {
                        "ask_n_obs": 30, "ask_mean": 45.0, "ask_std": 20.0, "ask_min": 10.0, "ask_max": 80.0,
                        "ask_p10": 15.0, "ask_p25": 25.0, "ask_p50": 45.0, "ask_p75": 65.0, "ask_p90": 75.0, "ask_trend": -0.3,
                        "bid_n_obs": 30, "bid_mean": -110.0, "bid_std": 15.0, "bid_min": -140.0, "bid_max": -80.0,
                        "bid_p10": -135.0, "bid_p25": -125.0, "bid_p50": -110.0, "bid_p75": -95.0, "bid_p90": -85.0, "bid_trend": 0.1,
                        "trade_n_obs": 10, "trade_mean": -30.0, "trade_std": 20.0, "trade_min": -50.0, "trade_max": -10.0,
                        "trade_p10": -48.0, "trade_p25": -42.0, "trade_p50": -30.0, "trade_p75": -18.0, "trade_p90": -12.0, "trade_trend": 0.5,
                        "spread_mean": 155.0,
                    },
                },
                "max_rational_bid": 150.0,
            },
            {
                "name": "Zero spread",   # spread = best_ask - best_bid = 0
                "private_values": [200.0, 150.0, 100.0, 50.0, 0.0],
                "market_history": {
                    "timestep": 500,
                    "market_trades": [{"time": 490, "price": 0.0}],
                    "total_trades": 20,
                },
                "market_state": {
                    "best_bid": 0.0, "best_ask": 0.0,
                    "units_available": 3, "q_max": 10,
                    "fundamental_estimate": 0.0,
                    "max_bid": 100.0, "min_ask": 100.0,
                    "inference": {
                        "ask_n_obs": 50, "ask_mean": 5.0, "ask_std": 10.0, "ask_min": -20.0, "ask_max": 30.0,
                        "ask_p10": -10.0, "ask_p25": -2.0, "ask_p50": 5.0, "ask_p75": 12.0, "ask_p90": 20.0, "ask_trend": -0.1,
                        "bid_n_obs": 50, "bid_mean": -5.0, "bid_std": 10.0, "bid_min": -30.0, "bid_max": 20.0,
                        "bid_p10": -20.0, "bid_p25": -12.0, "bid_p50": -5.0, "bid_p75": 2.0, "bid_p90": 10.0, "bid_trend": 0.0,
                        "trade_n_obs": 20, "trade_mean": 0.0, "trade_std": 5.0, "trade_min": -10.0, "trade_max": 10.0,
                        "trade_p10": -8.0, "trade_p25": -4.0, "trade_p50": 0.0, "trade_p75": 4.0, "trade_p90": 8.0, "trade_trend": 0.0,
                        "spread_mean": 10.0,
                    },
                },
                "max_rational_bid": 100.0,
            },
            {
                "name": "Late game (1 unit left)",
                "private_values": [200.0, 150.0, 100.0, 50.0, 0.0],
                "market_history": {
                    "timestep": 900,
                    "market_trades": [{"time": t, "price": float(-50 + t)} for t in range(5)],
                    "total_trades": 50,
                },
                "market_state": {
                    "best_bid": -20.0, "best_ask": 30.0,
                    "units_available": 1, "q_max": 10,
                    "fundamental_estimate": 2.0,
                    "max_bid": 50.0, "min_ask": 50.0,
                    "inference": {
                        "ask_n_obs": 90, "ask_mean": 25.0, "ask_std": 8.0, "ask_min": 5.0, "ask_max": 45.0,
                        "ask_p10": 15.0, "ask_p25": 19.0, "ask_p50": 25.0, "ask_p75": 31.0, "ask_p90": 38.0, "ask_trend": 0.2,
                        "bid_n_obs": 90, "bid_mean": -22.0, "bid_std": 8.0, "bid_min": -40.0, "bid_max": -5.0,
                        "bid_p10": -33.0, "bid_p25": -28.0, "bid_p50": -22.0, "bid_p75": -16.0, "bid_p90": -11.0, "bid_trend": 0.1,
                        "trade_n_obs": 50, "trade_mean": -12.0, "trade_std": 10.0, "trade_min": -50.0, "trade_max": 4.0,
                        "trade_p10": -46.0, "trade_p25": -41.0, "trade_p50": -12.0, "trade_p75": -4.0, "trade_p90": 2.0, "trade_trend": 0.8,
                        "spread_mean": 47.0,
                    },
                },
                "max_rational_bid": 50.0,
            },
            {
                "name": "Full units available",
                "private_values": [200.0, 150.0, 100.0, 50.0, 0.0],
                "market_history": {
                    "timestep": 100,
                    "market_trades": [{"time": 50, "price": -80.0}],
                    "total_trades": 3,
                },
                "market_state": {
                    "best_bid": -150.0, "best_ask": -50.0,
                    "units_available": 10, "q_max": 10,
                    "fundamental_estimate": -5.0,
                    "max_bid": 200.0, "min_ask": 200.0,
                    "inference": {
                        "ask_n_obs": 10, "ask_mean": -55.0, "ask_std": 12.0, "ask_min": -80.0, "ask_max": -30.0,
                        "ask_p10": -76.0, "ask_p25": -65.0, "ask_p50": -55.0, "ask_p75": -45.0, "ask_p90": -36.0, "ask_trend": 0.5,
                        "bid_n_obs": 10, "bid_mean": -155.0, "bid_std": 12.0, "bid_min": -180.0, "bid_max": -130.0,
                        "bid_p10": -176.0, "bid_p25": -165.0, "bid_p50": -155.0, "bid_p75": -145.0, "bid_p90": -136.0, "bid_trend": -0.2,
                        "trade_n_obs": 3, "trade_mean": -80.0, "trade_std": None, "trade_min": -80.0, "trade_max": -80.0,
                        "trade_p10": -80.0, "trade_p25": -80.0, "trade_p50": -80.0, "trade_p75": -80.0, "trade_p90": -80.0, "trade_trend": None,
                        "spread_mean": 100.0,
                    },
                },
                "max_rational_bid": 200.0,
            },
        ]
        
        for test in test_cases:
            try:
                result = strategy_func(
                    test["private_values"],
                    test["market_history"],
                    test["market_state"],
                )
            except TypeError as e:
                if "NoneType" in str(e):
                    return False, (
                        f"{test['name']}: TypeError — compared None best_bid/best_ask without a None check. "
                        f"ALWAYS guard None values:\n"
                        f"  best_bid = market_state.get('best_bid')  # may be None\n"
                        f"  if best_bid is not None and best_bid > threshold: ...\n"
                        f"Safe default: always return (some_positive_number, 1)"
                    )
                return False, f"{test['name']}: TypeError: {e}"
            except KeyError as e:
                key = str(e).strip("'\"")
                return False, (
                    f"{test['name']}: KeyError: '{key}' is not a valid key. "
                    f"market_history keys: 'timestep', 'total_trades', 'market_trades'. "
                    f"market_state keys: 'max_bid', 'best_bid', 'best_ask', 'units_available', 'q_max', 'fundamental_estimate'. "
                    f"There is NO 'events', 'bids', 'asks', or 'timesteps' key."
                )
            except Exception as e:
                return False, f"{test['name']}: {str(e)}"
            else:
                if result is not None:
                    if not isinstance(result, (tuple, list)) or len(result) < 2:
                        return False, f"{test['name']}: Result must be (shade, 1)"

                    shade, qty = result[0], result[1]

                    if not isinstance(shade, (int, float)):
                        return False, (
                            f"{test['name']}: shade must be a number, got {type(shade).__name__} = {repr(shade)!r:.60}. "
                            f"Return (shade, 1) where shade is a non-negative float."
                        )

                    if shade < 0:
                        return False, (
                            f"{test['name']}: shade must be >= 0, got {shade:.1f}. "
                            f"Return a non-negative shade value."
                        )

                    if not isinstance(qty, (int, float)) or qty < 1:
                        return False, (
                            f"{test['name']}: quantity must be >= 1, got {qty}. "
                            f"Always return quantity=1."
                        )

                # Normal market test must return a shade, not None
                if test["name"] == "Normal market" and result is None:
                    return False, (
                        "Normal market: strategy returned None when a live market exists. "
                        "Always return (shade, 1) unconditionally — e.g. return (200, 1)."
                    )

        return True, None

    def generate_candidate_strategies(
        self,
        n: int,
        config: Optional[MarketConfig] = None,
    ) -> List[str]:
        """
        Generate N verified candidate strategies via N separate LLM calls —
        one focused prompt per slot — with up to max_inner_iterations retries each.

        When a previous winner exists:
          - Slot 0: refinement call — sees the winner's code, told to improve it
          - Slots 1..n-1: exploration calls — distinct strategy families, no winner code

        All prompts include the current MarketConfig (state) as raw JSON plus the
        diagnostic JSON and value table from the previous episode (no natural language).
        """
        import re as _re

        if config is None:
            config = self.market_configs[self.episode_count % len(self.market_configs)]

        # Build one prompt string per slot
        prompts: List[str] = []
        base_ctx = self._build_base_context(config)
        constraint = self._side_constraint()

        population = self._get_population(config)
        bandit = self._get_bandit(config)
        ucb_families = bandit.ranked_families()  # UCB-ranked, best arm first

        if self.last_winner_reasoning and self.last_winner_code:
            # ── Slot 0: REFINE the all-time best from the population ──────
            best_entry = self.value_table.best_for_config(config)
            if best_entry and best_entry.get("best_code"):
                best_code_to_refine = best_entry["best_code"].strip()
                best_surplus_so_far = best_entry["best_surplus"]
            else:
                top = self.buffer.get_top_k_strategies(k=1)
                best_code_to_refine = top[0].strategy_code.strip() if top else self.last_winner_code
                best_surplus_so_far = None

            target_line = (
                f"The best surplus achieved so far for this market is ${best_surplus_so_far:.2f}. "
                f"Your goal is to BEAT this number."
                if best_surplus_so_far is not None
                else "Your goal is to maximise total surplus."
            )

            refine_prompt = "\n".join([
                base_ctx,
                "",
                self._strategy_example(),
                "",
                "## Your task: SUBSTANTIALLY IMPROVE the best strategy found so far",
                target_line,
                "The strategy below is the CURRENT BEST — but it is not good enough.",
                "You must make bold, meaningful changes. Do NOT just tweak a constant.",
                "Ideas for bigger improvements:",
                "  - Add a new signal (LOB depth, inventory urgency, trade-history momentum)",
                "  - Make the shade dynamic rather than static",
                "  - Add a regime switch: aggressive early, conservative late (or vice versa)",
                "  - Restructure the logic entirely if you think a different approach will win",
                "",
                f"Best strategy reasoning: \"{self.last_winner_reasoning}\"",
                "```python",
                best_code_to_refine,
                "```",
                "",
                "## Constraints",
                f"  - {constraint}",
                "  - Return a non-negative shade float — the simulator applies it directly (bid = pv - shade). Do NOT compute a bid price.",
                "  - Always guard best_bid/best_ask for None before using them.",
                "",
                "Respond with exactly ONE ```python``` block containing the complete agent_strategy function.",
                "The function signature MUST be: def agent_strategy(private_values, market_history, market_state)",
                "Access market data via: market_state.get('best_bid'), market_state.get('best_ask'), market_state['q_max'], market_state['units_available']",
                "Include a 1-2 sentence docstring describing what you changed and why you expect it to earn more surplus.",
            ])
            prompts.append(refine_prompt)

            # ── Slot 1: RECOMBINE top-2 diverse population programs ───────
            if n >= 2:
                diverse = population.diverse_sample(2)
                if len(diverse) >= 2:
                    crossover_prompt = "\n".join([
                        base_ctx,
                        "",
                        self._strategy_example(),
                        "",
                        "## Your task: RECOMBINE the two best strategies below into a single better strategy",
                        f"Program A earns avg surplus ${diverse[0].avg_surplus:.0f} (family: '{diverse[0].family_tag}')",
                        f"Program B earns avg surplus ${diverse[1].avg_surplus:.0f} (family: '{diverse[1].family_tag}')",
                        "Identify what makes each one strong, then write a NEW function that combines the best elements of both.",
                        "Do NOT simply copy one of them — the recombination should be genuinely different.",
                        "",
                        f"Program A:\n```python\n{diverse[0].code.strip()}\n```",
                        "",
                        f"Program B:\n```python\n{diverse[1].code.strip()}\n```",
                        "",
                        "## Constraints",
                        f"  - {constraint}",
                        "  - Return a non-negative shade float — the simulator applies it directly (bid = pv - shade).",
                        "  - Always guard best_bid/best_ask for None before using them.",
                        "",
                        "Respond with exactly ONE ```python``` block containing the complete agent_strategy function.",
                        "The function signature MUST be: def agent_strategy(private_values, market_history, market_state)",
                        "Include a 1-2 sentence docstring explaining what you took from each program and why the combination should outperform both.",
                    ])
                    prompts.append(crossover_prompt)
                else:
                    # Not enough population entries yet — fall back to PV-aware slot
                    pv_prompt = "\n".join([
                        base_ctx, "", self._strategy_example(), "",
                        "## Your task: design a private-values-aware bidding strategy",
                        "Use private_values[units_already_bought] to set shade — smaller shade for high-value units, larger for low-value ones.",
                        "", "## Constraints", f"  - {constraint}",
                        "  - Return a non-negative shade float. Always guard private_values index bounds.",
                        "", "Respond with exactly ONE ```python``` block.",
                        "The function signature MUST be: def agent_strategy(private_values, market_history, market_state)",
                        "Include a 1-2 sentence docstring.",
                    ])
                    prompts.append(pv_prompt)

            # ── Remaining slots: UCB-ranked exploration families ──────────
            for slot_i in range(n - 2):
                family = ucb_families[slot_i % len(ucb_families)]
                explore_prompt = "\n".join([
                    base_ctx,
                    "",
                    self._strategy_example(),
                    "",
                    "## Your task: design a SIMPLE ZI bidding strategy",
                    f"Implement this specific approach: {family}",
                    "",
                    "IMPORTANT: keep it simple and ZI-like.",
                    "Focus on learning a good fixed shade or bounded shade range for this state.",
                    "",
                    "## Constraints",
                    f"  - {constraint}",
                    "  - Return a non-negative shade float — the simulator applies it directly (bid = pv - shade). Do NOT compute a bid price.",
                    "  - Always guard best_bid/best_ask for None before using them.",
                    "  - Larger shade = more conservative (larger gap from private value, fewer executions); smaller = more aggressive.",
                    "",
                    "Respond with exactly ONE ```python``` block containing the complete agent_strategy function.",
                    "The function signature MUST be: def agent_strategy(private_values, market_history, market_state)",
                    "Access market data via: market_state.get('best_bid'), market_state.get('best_ask'), market_state['q_max'], market_state['units_available']",
                    "Include a 1-2 sentence docstring describing the chosen ZI shading rule and expected benefit.",
                ])
                prompts.append(explore_prompt)
        else:
            # Episode 1 — pure exploration via UCB-ranked families
            for slot_i in range(n - 1):
                family = ucb_families[slot_i % len(ucb_families)]
                explore_prompt = "\n".join([
                    base_ctx,
                    "",
                    self._strategy_example(),
                    "",
                    "## Your task: design a SIMPLE ZI bidding strategy",
                    f"Implement this specific approach: {family}",
                    "",
                    "IMPORTANT: keep it simple and ZI-like.",
                    "Focus on learning a good fixed shade or bounded shade range for this state.",
                    "",
                    "## Constraints",
                    f"  - {constraint}",
                    "  - Return a non-negative shade float — the simulator applies it directly (bid = pv - shade). Do NOT compute a bid price.",
                    "  - Always guard best_bid/best_ask for None before using them.",
                    "  - Larger shade = more conservative (larger gap from private value, fewer executions); smaller = more aggressive.",
                    "",
                    "Respond with exactly ONE ```python``` block containing the complete agent_strategy function.",
                    "The function signature MUST be: def agent_strategy(private_values, market_history, market_state)",
                    "Access market data via: market_state.get('best_bid'), market_state.get('best_ask'), market_state['q_max'], market_state['units_available']",
                    "Include a 1-2 sentence docstring describing the chosen ZI shading rule and expected benefit.",
                ])
                prompts.append(explore_prompt)
            # Last slot — private-values-aware
            pv_prompt = "\n".join([
                base_ctx,
                "",
                self._strategy_example(),
                "",
                "## Your task: design a private-values-aware bidding strategy",
                "Use the private_values list to bid differently depending on how valuable the next unit is to you.",
                "private_values[i] is your RELATIVE value for unit i (already relative to fundamental — same scale as max_bid).",
                "private_values[0] is the value for the first unit you'd buy, private_values[1] for the second, etc.",
                "units_already_bought = market_state['q_max'] - market_state['units_available']",
                "Your value for the NEXT unit = private_values[units_already_bought] (if in range).",
                "Strategy: return smaller shade (more aggressive) when your next-unit value is high; return larger shade (more conservative) when it is low.",
                "",
                "## Constraints",
                f"  - {constraint}",
                "  - Return a non-negative shade float — the simulator applies it directly (bid = pv - shade). Do NOT compute a bid price.",
                "  - Always guard best_bid/best_ask for None before using them.",
                "  - Always guard private_values index bounds.",
                "",
                "Respond with exactly ONE ```python``` block containing the complete agent_strategy function.",
                "The function signature MUST be: def agent_strategy(private_values, market_history, market_state)",
                "Access market data via: market_state.get('best_bid'), market_state.get('best_ask'), market_state['q_max'], market_state['units_available']",
                "Include a 1-2 sentence docstring describing your approach.",
            ])
            prompts.append(pv_prompt)

        # Assign a family tag to each prompt slot for the bandit
        # Slots: 0=refine, 1=crossover (or pv), 2..n-1=exploration families
        slot_family_tags: List[str] = []
        if self.last_winner_reasoning and self.last_winner_code:
            slot_family_tags.append("refine")
            slot_family_tags.append("crossover")
            for slot_i in range(len(prompts) - 2):
                slot_family_tags.append(ucb_families[slot_i % len(ucb_families)])
        else:
            for slot_i in range(len(prompts) - 1):
                slot_family_tags.append(ucb_families[slot_i % len(ucb_families)])
            slot_family_tags.append("private_values")

        # Per-slot: call LLM, verify, retry up to max_inner_iterations
        verified: List[str] = []
        verified_family_tags: List[str] = []  # parallel list of family tags for bandit
        for i, prompt in enumerate(prompts):
            tag = f"Candidate {i+1}"
            code = ""
            passes, err = False, "no code generated"

            for attempt in range(self.max_inner_iterations):
                if attempt == 0:
                    current_prompt = prompt
                else:
                    # Compact repair prompt — strip the base context, focus only on fixing the bug
                    current_prompt = "\n".join([
                        "## Fix this broken agent_strategy function",
                        "",
                        "The function below failed with this error:",
                        f"  ERROR: {err}",
                        "",
                        "Broken code:",
                        f"```python",
                        code,
                        "```",
                        "",
                        self._strategy_example(),
                        "",
                        "## Common mistakes to avoid",
                        "  - You are a ZI agent: return shade (a non-negative float), NOT a bid price",
                        "  - Do NOT compute 'max_bid - shade' and return that — return the shade value directly",
                        "  - market_trades is List[dict]: access price as trade['price'], NOT as a plain number",
                        "  - There is NO market_history['events'] key — use market_history['market_trades'] for trades",
                        "  - There is NO market_state['timesteps'] key — use market_history['timestep']",
                        "  - There is NO market_state['bids_relative'] or 'asks_relative'] — those are offline-context-only fields",
                        "  - best_bid and best_ask can be None — ALWAYS check 'if best_bid is not None' before any arithmetic",
                        "  - If computing spread = best_ask - best_bid, first guard BOTH are not None",
                        "  - Return (shade, 1) — NOT a list, NOT None, NOT private_values, NOT a bid price",
                        f"  - {self._side_constraint()}",
                        "",
                        "Respond with ONLY the corrected ```python``` block. Fix the error above.",
                    ])

                try:
                    response = self.code_gen.generator.client.chat.completions.create(
                        model=self.code_gen.generator.model_name,
                        messages=[
                            {"role": "system", "content": (
                                "You are an expert algorithmic trading agent designer writing Python bidding strategies for a continuous double auction market. "
                                "Strategies must use only the market_state and market_history dicts provided — no external data, no ML libraries. "
                                "Only math, numpy, random, and statistics may be imported."
                            )},
                            {"role": "user", "content": current_prompt},
                        ],
                        temperature=0.7 if attempt == 0 else 0.3,
                        max_tokens=1000,
                    )
                    raw = response.choices[0].message.content
                except Exception as e:
                    print(f"  [{tag}] LLM call failed: {e}")
                    break

                blocks = _re.findall(r"```python\s*(.*?)\s*```", raw, _re.DOTALL | _re.IGNORECASE)
                if not blocks:
                    blocks = _re.findall(r"```\w*\s*(.*?)\s*```", raw, _re.DOTALL)
                code = blocks[0].strip() if blocks else raw.strip()
                # Strip any leading language-tag line (e.g. "Python\n" or "python\n")
                code_lines = code.splitlines()
                if code_lines and _re.fullmatch(r"[A-Za-z]+", code_lines[0].strip()):
                    code = "\n".join(code_lines[1:]).strip()

                if not code or "def agent_strategy" not in code:
                    err = "missing agent_strategy function"
                    passes = False
                else:
                    passes, err = self.verify_strategy(code)

                if passes:
                    reasoning = self._extract_reasoning(code) or "(no docstring)"
                    attempt_str = f" (attempt {attempt+1})" if attempt > 0 else ""
                    print(f"  [{tag}] ✓{attempt_str}  {reasoning}")
                    verified.append(code)
                    ftag = slot_family_tags[i] if i < len(slot_family_tags) else "unknown"
                    verified_family_tags.append(ftag)
                    break
                else:
                    if attempt < self.max_inner_iterations - 1:
                        print(f"  [{tag}] ✗ attempt {attempt+1}: {err} — retrying...")
                    else:
                        print(f"  [{tag}] ✗ all {self.max_inner_iterations} attempts failed: {err}")

        return verified, verified_family_tags

    def _side_constraint(self) -> str:
        if self.llm_order_type == BUY:
            return "Return (shade, 1) where shade >= 0. The simulator bids pv - shade directly."
        return "Return (shade, 1) where shade >= 0. The simulator asks pv + shade directly."

    def _exploration_families(self, config: Optional[MarketConfig] = None) -> List[str]:
        if self._dynamic_families is None:
            if config is None:
                config = self.market_configs[0]
            self._dynamic_families = self._bootstrap_families_from_data(config)
        return list(self._dynamic_families)

    def _strategy_example(self) -> str:
        """Minimal interface reminder shown in every prompt."""
        return "\n".join([
            "## Interface",
            "Return (shade, 1) where shade>=0. bid=private_value-shade (buyer), ask=private_value+shade (seller).",
            "Args: private_values:List[float], market_history:dict, market_state:dict",
            "market_history keys: timestep(int), total_trades(int), market_trades(List[{time,price}])",
            "market_state keys: max_bid, best_bid(None ok), best_ask(None ok), units_available, q_max, fundamental_estimate",
            "Phase-1 goal: keep strategy simple and ZI-like; focus on learning a good shading constant/range.",
            "Offline event log (learn from, NOT available at runtime): events[i]['lob']['bids_relative'] and ['asks_relative'] are top-4 LOB depth arrays",
            "Rules: never return None; shade>=0; guard best_bid/best_ask for None; trade['price'] is a float",
            "",
            "```python",
            "def agent_strategy(private_values, market_history, market_state):",
            '    \"\"\"Example: fixed shade 200.\"\"\"',
            "    return (200, 1)",
            "```",
        ])

    def _run_diagnostic(
        self,
        candidates: List[str],
        episode_number: int,
        config: MarketConfig,
    ) -> Tuple[str, Dict[str, Any]]:
        """
        Diagnostic selection: run ONE sim per candidate at the config's fixed seed.
        Winner = highest surplus.  Returns (winning_code, diagnostic_summary).

        The fixed seed guarantees all candidates face the same market draw, making
        the surplus comparison fair and reproducible.  The full diagnostic_json
        (capture_detail=True) is collected for the winning candidate and stored as
        the context for the next episode's prompt.
        """
        import numpy as _np
        import math as _math

        # Generate the fixed seed list used for ALL candidates — same 50 seeds every time
        base_seed = config.diagnostic_seed(episode_number)
        seeds = [base_seed + i for i in range(self.num_eval_seeds)]

        print(f"\n[Diagnostic] Evaluating {len(candidates)} candidates over "
              f"{self.num_eval_seeds} seeds (base={base_seed}, config={config}) ...")

        best_code = candidates[0]
        best_avg_surplus = -float('inf')
        best_ci = 0
        best_batch: Optional[Dict] = None
        results = []
        # Consumer surplus depends only on private values drawn from each seed,
        # not on the strategy — so it is identical across all candidates.
        # We collect it once from candidate 0 and reuse for the summary.
        shared_consumer_surpluses: List[float] = []
        shared_consumer_avg: Optional[float] = None

        for ci, code in enumerate(candidates):
            namespace = {"np": _np, "numpy": _np, "math": _math}
            exec(code, namespace)
            strategy_func = namespace['agent_strategy']
            reasoning = self._extract_reasoning(code) or "(no docstring)"

            surpluses: List[float] = []
            zi_surpluses: List[float] = []
            per_units: List[float] = []
            shades: List[float] = []
            units_exec_list: List[int] = []
            positive_pv_counts: List[int] = []  # number of units with pv > 0 per seed
            last_result: Optional[Dict] = None

            for seed in seeds:
                try:
                    r = run_episode(
                        llm_strategy_func=strategy_func,
                        llm_order_type=self.llm_order_type,
                        llm_private_values=config.fixed_private_values_relative,
                        num_zi_buy=config.num_zi_buy,
                        num_zi_sell=config.num_zi_sell,
                        timesteps=config.timesteps,
                        q_max=config.q_max,
                        pv_var=config.pv_var,
                        shade_range=config.shade_range,
                        random_seed=seed,
                        capture_detail=(seed == base_seed),  # capture detail only for first seed
                    )
                except Exception as e:
                    print(f"  Candidate {ci+1} seed {seed}: crashed ({type(e).__name__}: {e}) — skipping")
                    continue
                surpluses.append(r["llm_surplus"])
                if ci == 0:
                    shared_consumer_surpluses.append(r.get("consumer_surplus", 0.0))
                zi_surpluses.append(r["avg_zi_same_surplus"])
                per_units.append(r["per_unit_surplus"])
                if r["avg_shade"] is not None:
                    shades.append(r["avg_shade"])
                units_exec_list.append(r["llm_units_executed"])
                # Count units with positive private value — this is the natural exec target
                pvs = r.get("llm_private_values_relative", [])
                positive_pv_counts.append(sum(1 for pv in pvs if pv > 0))
                if seed == base_seed:
                    last_result = r

            if not surpluses:
                print(f"  Candidate {ci+1}: all seeds crashed — disqualified")
                results.append({"candidate": ci+1, "avg_surplus": None, "reasoning": reasoning})
                continue

            avg_surplus = sum(surpluses) / len(surpluses)
            std_surplus = (sum((s - avg_surplus)**2 for s in surpluses) / len(surpluses))**0.5
            if ci == 0 and shared_consumer_surpluses:
                shared_consumer_avg = sum(shared_consumer_surpluses) / len(shared_consumer_surpluses)
            avg_zi = sum(zi_surpluses) / len(zi_surpluses)
            avg_per_unit = sum(per_units) / len(per_units)
            avg_shade_val = sum(shades) / len(shades) if shades else None
            avg_units = sum(units_exec_list) / len(units_exec_list)
            avg_exec_ratio = avg_units / config.q_max
            # Neutral exec ratio: avg fraction of units with pv > 0 — no bonus/penalty here
            avg_positive_pvs = sum(positive_pv_counts) / len(positive_pv_counts) if positive_pv_counts else config.q_max
            neutral_exec_ratio = avg_positive_pvs / config.q_max

            # Phase-1 simple objective: raw average surplus is the selection score.
            shaped_score = avg_surplus
            cs_pct = f"{avg_surplus / shared_consumer_avg * 100:.0f}%" if shared_consumer_avg else "N/A"

            batch_summary = {
                "avg_surplus": round(avg_surplus, 4),
                "selection_score": round(shaped_score, 4),
                "std_surplus": round(std_surplus, 4),
                "avg_zi_same_surplus": round(avg_zi, 4),
                "avg_per_unit_surplus": round(avg_per_unit, 4),
                "avg_shade": round(avg_shade_val, 4) if avg_shade_val is not None else None,
                "avg_units_executed": round(avg_units, 2),
                "avg_exec_ratio": round(avg_exec_ratio, 4),
                "num_seeds": len(surpluses),
                "last_result": last_result,  # detail run from base_seed
            }

            marker = ""
            if shaped_score > best_avg_surplus:
                best_avg_surplus = shaped_score
                best_code = code
                best_ci = ci
                best_batch = batch_summary
                marker = " ◀ leading"

            beat = "▲" if avg_surplus > avg_zi else "▼"
            print(f"  Candidate {ci+1}: avg=${avg_surplus:.2f} ±{std_surplus:.0f}  "
                  f"cs={cs_pct}  zi=${avg_zi:.0f} {beat}  "
                  f"exec={avg_exec_ratio*100:.0f}%  {reasoning[:50]}{marker}")
            results.append({"candidate": ci+1, "reasoning": reasoning, **batch_summary})

            best_raw_surplus = (best_batch or {}).get("avg_surplus", best_avg_surplus)
            best_selection = (best_batch or {}).get("selection_score", best_avg_surplus)
        cs_ratio = f"  ({best_raw_surplus/shared_consumer_avg*100:.0f}% of CS)" if shared_consumer_avg else ""
        print(f"  → Winner: Candidate {best_ci + 1}  raw=${best_raw_surplus:.2f}  "
              f"score={best_selection:.1f}{cs_ratio}")

        if shared_consumer_avg is not None:
            print(f"  (Consumer surplus: ${shared_consumer_avg:.2f} — same for all candidates)")

        return best_code, {
            "diagnostic_results": results,
            "winner_avg_surplus": best_raw_surplus,   # raw surplus for value table / buffer
            "winner_selection_score": best_selection,
            "winner_batch": best_batch,
            "shared_consumer_surplus": round(shared_consumer_avg, 4) if shared_consumer_avg is not None else None,
            "base_seed": base_seed,
            "num_eval_seeds": self.num_eval_seeds,
        }

    def _run_batches(
        self,
        strategy_func: Callable,
        episode_number: int,
        config: Optional[MarketConfig] = None,
    ) -> Dict[str, Any]:
        """
        Retained for backwards-compatibility but no longer called in the main loop.
        Can be used externally for extended evaluation of a winner.
        """
        if config is None:
            config = self.market_configs[0]
        num_batches = 10  # small default for manual use
        surpluses: List[float] = []
        per_units: List[float] = []
        exec_ratios: List[float] = []
        shades: List[float] = []
        zi_surpluses: List[float] = []
        total_units_exec = 0

        for b in range(num_batches):
            seed = episode_number * 1000 + b
            try:
                result = run_episode(
                    llm_strategy_func=strategy_func,
                    llm_order_type=self.llm_order_type,
                    llm_private_values=config.fixed_private_values_relative,
                    num_zi_buy=config.num_zi_buy,
                    num_zi_sell=config.num_zi_sell,
                    timesteps=config.timesteps,
                    q_max=config.q_max,
                    pv_var=config.pv_var,
                    shade_range=config.shade_range,
                    random_seed=seed,
                )
            except (RecursionError, Exception) as e:
                print(f"  [Batch {b}] crashed: {type(e).__name__}: {e} — skipping")
                continue
            surpluses.append(result["llm_surplus"])
            per_units.append(result["per_unit_surplus"])
            exec_ratios.append(result["episode_stats"]["execution_ratio"])
            if result["avg_shade"] is not None:
                shades.append(result["avg_shade"])
            total_units_exec += result["llm_units_executed"]
            zi_surpluses.append(result["avg_zi_same_surplus"])

        if not surpluses:
            return {"avg_surplus": 0.0, "std_surplus": 0.0, "avg_per_unit": 0.0,
                    "avg_exec_ratio": 0.0, "avg_shade": None, "total_units_exec": 0,
                    "num_batches": 0, "avg_zi_same_surplus": 0.0}

        avg_surplus = sum(surpluses) / len(surpluses)
        std_surplus = (sum((s - avg_surplus) ** 2 for s in surpluses) / len(surpluses)) ** 0.5
        avg_zi = sum(zi_surpluses) / len(zi_surpluses)

        return {
            "avg_surplus": avg_surplus,
            "std_surplus": std_surplus,
            "avg_per_unit": sum(per_units) / len(per_units),
            "avg_exec_ratio": sum(exec_ratios) / len(exec_ratios),
            "avg_shade": sum(shades) / len(shades) if shades else None,
            "total_units_exec": total_units_exec,
            "num_batches": num_batches,
            "avg_zi_same_surplus": avg_zi,
        }

    @staticmethod
    def _summarize_winner_metrics(
        winner_batch: Optional[Dict[str, Any]],
        diagnostic_summary: Optional[Dict[str, Any]],
        winner_result: Dict[str, Any],
        q_max: int,
        num_eval_seeds: int,
    ) -> Dict[str, Any]:
        """Return unified winner metrics from batched or single-run diagnostic output."""
        if winner_batch:
            return {
                "utility": winner_batch.get("avg_surplus", 0.0),
                "consumer_surplus": (diagnostic_summary or {}).get("shared_consumer_surplus", None),
                "avg_zi": winner_batch.get("avg_zi_same_surplus", 0.0),
                "per_unit_surplus": winner_batch.get("avg_per_unit_surplus", 0.0),
                "avg_shade": winner_batch.get("avg_shade", None),
                "units_executed": winner_batch.get("avg_units_executed", 0),
                "execution_ratio": winner_batch.get("avg_exec_ratio", 0.0),
                "std_surplus": winner_batch.get("std_surplus", None),
                "num_seeds": winner_batch.get("num_seeds", num_eval_seeds),
                "q_max": q_max,
            }

        return {
            "utility": winner_result.get("llm_surplus", 0.0),
            "consumer_surplus": winner_result.get("consumer_surplus", None),
            "avg_zi": winner_result.get("avg_zi_same_surplus", 0.0),
            "per_unit_surplus": winner_result.get("per_unit_surplus", 0.0),
            "avg_shade": winner_result.get("avg_shade", None),
            "units_executed": winner_result.get("llm_units_executed", 0),
            "execution_ratio": winner_result.get("episode_stats", {}).get("execution_ratio", 0.0),
            "std_surplus": None,
            "num_seeds": 1,
            "q_max": q_max,
        }

    @staticmethod
    def _print_winner_metrics(metrics: Dict[str, Any]) -> None:
        """Print a consistent winner diagnostic summary to stdout."""
        seeds_label = f" (avg over {metrics['num_seeds']} seeds)" if metrics["num_seeds"] > 1 else ""
        std_label = f"  ±{metrics['std_surplus']:.1f}" if metrics["std_surplus"] is not None else ""
        consumer_label = (
            f"${metrics['consumer_surplus']:.2f}"
            if metrics["consumer_surplus"] is not None
            else "N/A"
        )
        shade_label = f"{metrics['avg_shade']:.1f}" if metrics["avg_shade"] is not None else "N/A"
        print(f"\n[Episode] Diagnostic Result (winner){seeds_label}:")
        print(f"  Surplus:          ${metrics['utility']:.2f}{std_label}")
        print(f"  Consumer Surplus: {consumer_label}")
        print(
            f"  ZI (same):        ${metrics['avg_zi']:.2f}  "
            f"({'▲ LLM beats ZI' if metrics['utility'] > metrics['avg_zi'] else '▼ ZI beats LLM'})"
        )
        print(f"  Per-Unit:         ${metrics['per_unit_surplus']:.2f}")
        print(f"  Shade:            {shade_label}")
        if metrics["num_seeds"] > 1:
            print(f"  Units Exec:       {metrics['units_executed']:.1f} / {metrics['q_max']}")
        else:
            print(f"  Units Exec:       {int(metrics['units_executed'])} / {metrics['q_max']}")
        print(f"  Exec Rate:        {metrics['execution_ratio']*100:.1f}%")

    def _resolve_winner_result(
        self,
        best_code: str,
        episode_number: int,
        config: MarketConfig,
        diagnostic_summary: Optional[Dict[str, Any]],
    ) -> Tuple[Optional[Dict[str, Any]], Dict[str, Any]]:
        """Return (winner_batch, winner_result), running fallback diagnostic when needed."""
        winner_batch = (diagnostic_summary or {}).get("winner_batch")
        winner_result = (winner_batch or {}).get("last_result") if winner_batch else None

        if winner_result is not None:
            return winner_batch, winner_result

        import numpy as _np
        import math as _math
        ns = {"np": _np, "numpy": _np, "math": _math}
        exec(best_code, ns)
        try:
            winner_result = run_episode(
                llm_strategy_func=ns['agent_strategy'],
                llm_order_type=self.llm_order_type,
                llm_private_values=config.fixed_private_values_relative,
                num_zi_buy=config.num_zi_buy,
                num_zi_sell=config.num_zi_sell,
                timesteps=config.timesteps,
                q_max=config.q_max,
                pv_var=config.pv_var,
                shade_range=config.shade_range,
                random_seed=config.diagnostic_seed(episode_number),
                capture_detail=True,
            )
        except Exception as e:
            print(f"[Episode] Warning: winner diagnostic failed: {e}")
            winner_result = {}
        return None, winner_result

    @staticmethod
    def _winner_family_from_summary(
        diagnostic_summary: Optional[Dict[str, Any]],
        utility: float,
        candidate_family_tags: List[str],
        fallback_family: Optional[str],
    ) -> str:
        """Infer winner family tag from diagnostic summary, with safe fallback."""
        diag_results = (diagnostic_summary or {}).get("diagnostic_results", [])
        winner_ci = next(
            (
                r["candidate"] - 1
                for r in diag_results
                if r.get("avg_surplus") is not None and abs(r["avg_surplus"] - utility) < 0.01
            ),
            0,
        )
        if candidate_family_tags and winner_ci < len(candidate_family_tags):
            return candidate_family_tags[winner_ci]
        return fallback_family or "unknown"

    def run_episode(self, episode_number: int) -> Dict[str, Any]:
        """
        Run a single episode.

        RL step:
          1. Pick state s_k = market_configs[k % len(configs)]
          2. Generate N candidate strategies (policy π inference)
          3. Run ONE diagnostic sim per candidate at fixed seed (same for all) → rewards
          4. Select winner = highest surplus
          5. Update value table V(s_k)
          6. Store diagnostic JSON in buffer for next episode's context
        """
        # Pick state for this episode (round-robin)
        config = self.market_configs[self.episode_count % len(self.market_configs)]

        print(f"\n{'='*60}")
        print(f"EPISODE {episode_number}  |  State: {config}")
        print(f"{'='*60}")

        best_code = None
        diagnostic_summary = None

        candidate_family_tags: List[str] = []
        if self.num_candidates > 1:
            print(f"\n[Policy] Requesting {self.num_candidates} candidate strategies...")
            verified_candidates, candidate_family_tags = self.generate_candidate_strategies(self.num_candidates, config=config)

            if len(verified_candidates) >= 2:
                best_code, diagnostic_summary = self._run_diagnostic(
                    verified_candidates, episode_number, config
                )
            elif len(verified_candidates) == 1:
                print("[Policy] Only 1 candidate passed verification.")
                best_code = verified_candidates[0]
                # Still run diagnostic on the single candidate to get diagnostic_json
                _, diagnostic_summary = self._run_diagnostic([best_code], episode_number, config)
            else:
                print("[Policy] No candidates passed, falling back to single-strategy loop.")

        if best_code is None:
            error_feedback = None
            previous_attempt = None
            for inner_iter in range(self.max_inner_iterations):
                print(f"\n[Inner Loop {inner_iter}] Generating strategy...")
                candidate_code = self.generate_strategy_code(
                    iteration=inner_iter,
                    error_feedback=error_feedback,
                    previous_attempt=previous_attempt,
                    config=config,
                )
                passes, error_trace = self.verify_strategy(candidate_code, iteration=inner_iter)
                if passes:
                    print(f"[Inner Loop {inner_iter}] ✓ Strategy verified!")
                    best_code = candidate_code
                    break
                else:
                    print(f"[Inner Loop {inner_iter}] ✗ Verification failed: {error_trace}")
                    error_feedback = error_trace
                    previous_attempt = candidate_code

        if best_code is None:
            print(f"Failed to generate any verified strategy for episode {episode_number}")
            return {"episode_number": episode_number, "success": False,
                    "error": "Could not generate verified code"}

        # ── Get final diagnostic result for the winner ──────────────────
        winner_batch, winner_result = self._resolve_winner_result(
            best_code=best_code,
            episode_number=episode_number,
            config=config,
            diagnostic_summary=diagnostic_summary,
        )

        metrics = self._summarize_winner_metrics(
            winner_batch=winner_batch,
            diagnostic_summary=diagnostic_summary,
            winner_result=winner_result,
            q_max=config.q_max,
            num_eval_seeds=self.num_eval_seeds,
        )
        utility = metrics["utility"]
        avg_zi = metrics["avg_zi"]
        per_unit_surplus = metrics["per_unit_surplus"]
        avg_shade = metrics["avg_shade"]
        units_executed = metrics["units_executed"]
        execution_ratio = metrics["execution_ratio"]

        self._print_winner_metrics(metrics)

        # ── Update value table V(s) ─────────────────────────────────────
        is_new_best = self.value_table.update(config, episode_number, utility, best_code)
        if is_new_best:
            print(f"  ★ New best for state '{config.label or config.config_hash()}' (avg=${utility:.2f})!")

        # ── Update scored population (FunSearch island) ─────────────────
        winner_family = self._winner_family_from_summary(
            diagnostic_summary=diagnostic_summary,
            utility=utility,
            candidate_family_tags=candidate_family_tags,
            fallback_family=self.last_winner_family,
        )
        self._get_population(config).add(best_code, utility, winner_family, episode_number)
        self.last_winner_family = winner_family

        # ── Update UCB bandit with winner surplus ────────────────────────
        self._get_bandit(config).update(winner_family, utility)
        bandit_summary = self._get_bandit(config).summary()
        top_family = max(bandit_summary, key=lambda f: bandit_summary[f]["avg_surplus"])
        print(f"  [Bandit] winner_family='{winner_family}'  top_family='{top_family}'  "
              f"pop_size={len(self._get_population(config))}")

        # ── Update OPRO surplus history ──────────────────────────────────
        self._surplus_history.append((episode_number, utility))

        # ── Store in buffer for next episode's context ──────────────────
        self.buffer.add_episode(
            episode_number=episode_number,
            strategy_code=best_code,
            utility=utility,
            units_executed=units_executed,
            execution_ratio=execution_ratio,
            metadata={
                "config_hash": config.config_hash(),
                "config_label": config.label,
                "zi_opponents": config.num_zi_buy,
                "timesteps": config.timesteps,
                "per_unit_surplus": per_unit_surplus,
                "avg_shade": avg_shade,
            }
        )

        # ── Save diagnostic JSON for next episode's context ─────────────
        self.last_diagnostic_json = winner_result
        self.last_winner_reasoning = self._extract_reasoning(best_code)
        self.last_winner_code = best_code
        # last_winner_family already set above

        self.episode_count += 1
        result = {
            "episode_number": episode_number,
            "success": True,
            "utility": utility,
            "units_executed": units_executed,
            "execution_ratio": execution_ratio,
            "per_unit_surplus": per_unit_surplus,
            "avg_shade": avg_shade,
            "avg_zi_same_surplus": avg_zi,
            "strategy_code": best_code,
            "strategy_reasoning": self.last_winner_reasoning,
            "config": config.to_dict(),
            "diagnostic_summary": diagnostic_summary,
        }
        self.episode_results.append(result)
        return result

    def run_feedback_loop(self, num_episodes: int = 5) -> Dict[str, Any]:
        """
        Run the complete multi-state RL feedback loop for num_episodes episodes.

        Each episode:
          - Picks the next MarketConfig (state) round-robin
          - Generates N candidate strategies (policy inference)
          - Runs ONE diagnostic sim per candidate (same seed for all candidates)
          - Selects winner by surplus (reward), updates value table V(s)
          - Stores result in rolling buffer for next episode's context
        """
        print(f"\n{'='*70}")
        print(f"MULTI-STATE RL FEEDBACK LOOP PIPELINE")
        print(f"{'='*70}")
        print(f"Configuration:")
        print(f"  Episodes:          {num_episodes}")
        print(f"  Agent Type:        {'Buyer' if self.llm_order_type == BUY else 'Seller'}")
        print(f"  q_max:             {self.q_max}")
        print(f"  Candidates / ep:   {self.num_candidates}")
        print(f"  Eval seeds / cand: {self.num_eval_seeds}")
        print(f"  Max retries / cand:{self.max_inner_iterations}")
        print(f"  Buffer Size:       {self.buffer.buffer_size}")
        print(f"  State Space ({len(self.market_configs)} configs):")
        for cfg in self.market_configs:
            print(f"    {cfg}")

        for k in range(1, num_episodes + 1):
            result = self.run_episode(k)

            if result["success"]:
                episodes, utilities = self.buffer.get_utility_trend()
                best_util = self.buffer.get_best_utility()
                utils_fmt = [f"${u:.0f}" for u in utilities]
                print(f"\n[Buffer] Episodes: {episodes}  surpluses: {utils_fmt}  best: ${best_util:.2f}")
                print(f"[Value Table]\n{self.value_table.summary_table()}")

        # Final summary
        print(f"\n{'='*70}")
        print(f"FEEDBACK LOOP COMPLETE")
        print(f"{'='*70}")
        episodes, utilities = self.buffer.get_utility_trend()
        print(f"  Episodes Completed: {self.episode_count}")
        print(f"  Buffer: {len(self.buffer)} / {self.buffer.buffer_size} entries")
        print(f"  Surplus Trend: {[f'${u:.0f}' for u in utilities]}")
        print(f"  Best Surplus: ${self.buffer.get_best_utility():.2f}")
        print(f"\n[Final Value Table V(s)]")
        print(self.value_table.summary_table())

        return {
            "num_episodes": num_episodes,
            "episode_count": self.episode_count,
            "buffer": {
                "size": len(self.buffer),
                "max_size": self.buffer.buffer_size,
                "utilities": utilities,
                "episodes": episodes,
                "average_utility": self.buffer.get_average_utility(),
                "best_utility": self.buffer.get_best_utility(),
            },
            "value_table": json.loads(self.value_table.to_json()),
            "episode_results": self.episode_results,
        }
