"""
LLM-based trading agent that executes a strategy function generated by an LLM.

The agent's strategy is defined as executable Python code that maps:
    (private_values, market_history) -> action (bid/ask/withdraw)

The agent participates in market simulations and tracks its realized surplus.
"""

import inspect
from typing import Callable, Dict, List, Any, Optional, Tuple
from marketsim.agent.base_agent import Agent
from marketsim.fourheap.constants import BUY, SELL


class LLMAgent(Agent):
    """
    Agent that executes a strategy defined as Python code.
    
    The strategy function maps (private_values, market_history) to actions.
    The agent tracks its surplus over the episode.
    """
    
    def __init__(
        self,
        agent_id: int,
        order_type: int,  # BUY or SELL
        private_values: List[float],
        strategy_func: Callable,
        arrival_rate: float = 0.5,
    ):
        """
        Args:
            agent_id: Unique agent identifier
            order_type: BUY or SELL
            private_values: List of private valuations/costs (highest to lowest)
            strategy_func: Callable that takes (private_values, market_history) and returns (price, quantity)
                          or None to indicate no order
            arrival_rate: Rate at which agent arrives (1/lifetime of orders in timesteps)
        """
        super().__init__(agent_id, order_type)
        self.private_values = private_values
        self.strategy_func = strategy_func
        self.arrival_rate = arrival_rate
        
        # Track surplus
        self.executed_trades: List[Dict[str, float]] = []
        self.surplus = 0.0
        
        # Track units remaining
        self.units_available = len(private_values)
        self.units_executed = 0
        
    def get_private_values(self) -> List[float]:
        """Return this agent's private valuations/costs."""
        return self.private_values
    
    def execute_strategy(
        self,
        market_history: Dict[str, Any],
        best_bid: Optional[float] = None,
        best_ask: Optional[float] = None,
    ) -> Tuple[Optional[float], Optional[int]]:
        """
        Execute the strategy function to determine action.
        
        Args:
            market_history: Dict containing market state (transactions, order book state, etc)
            best_bid: Current best bid in market (optional, can be None)
            best_ask: Current best ask in market (optional, can be None)
        
        Returns:
            (price, quantity) or (None, None) to take no action
        """
        if self.units_executed >= self.units_available:
            return None, None
        
        try:
            # Try calling with market history
            sig = inspect.signature(self.strategy_func)
            params = list(sig.parameters.keys())
            
            if len(params) >= 3:
                # Expect (private_values, market_history, market_state)
                result = self.strategy_func(
                    self.private_values,
                    market_history,
                    {
                        "best_bid": best_bid,
                        "best_ask": best_ask,
                        "units_available": self.units_available - self.units_executed,
                    }
                )
            elif len(params) >= 2:
                # Expect (private_values, market_history)
                result = self.strategy_func(self.private_values, market_history)
            else:
                # Fallback
                result = self.strategy_func(self.private_values)
            
            # Parse result
            if result is None:
                return None, None
            
            if isinstance(result, (tuple, list)) and len(result) >= 2:
                price, quantity = result[0], result[1]
            else:
                price = result
                quantity = 1
            
            # Validate price
            if price is None:
                return None, None
            
            # Enforce rationality constraints
            if self.order_type == BUY:
                # Buyer cannot bid above valuation
                max_price = self.private_values[self.units_executed]
                if price > max_price:
                    price = max_price
            else:
                # Seller cannot ask below cost
                min_price = self.private_values[self.units_executed]
                if price < min_price:
                    price = min_price
            
            # Validate quantity
            quantity = int(max(1, min(quantity, self.units_available - self.units_executed)))
            
            return float(price), quantity
            
        except Exception as e:
            # If strategy fails, take no action
            print(f"Strategy execution error for agent {self.agent_id}: {e}")
            return None, None
    
    def record_execution(self, price: float) -> None:
        """Record that one unit was executed at given price."""
        self.executed_trades.append({"price": price})
        self.units_executed += 1
        
        # Calculate surplus for this unit
        if self.order_type == BUY:
            unit_surplus = self.private_values[self.units_executed - 1] - price
        else:
            unit_surplus = price - self.private_values[self.units_executed - 1]
        
        self.surplus += unit_surplus
    
    def get_surplus(self) -> float:
        """Return total realized surplus so far."""
        return self.surplus
    
    def get_units_executed(self) -> int:
        """Return number of units executed."""
        return self.units_executed
    
    def reset(self) -> None:
        """Reset for next episode."""
        self.executed_trades = []
        self.surplus = 0.0
        self.units_executed = 0
